name: Pre-2023 Website Deploy Test
on:
  workflow_dispatch:
  push: 
    branches:
      - 'main'
  pull_request: 
    branches:
      - 'main'
jobs:
  gh-pages-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Deploy ðŸš€
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: . # The folder the action should deploy.
  netlify-deploy:
    name: Netlify Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Non-Production PR Deploy
        if: github.event_name == 'pull_request'
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: '.'
          production-deploy: false
          deploy-message: "Non-Production PR Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: false
          overwrites-pull-request-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN_TEST_RM }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_TEST_RM }}
        timeout-minutes: 1
      - name: Production Deploy
        if: github.event_name == 'push'
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: '.'
          production-deploy: true
          deploy-message: "Production Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: false
          overwrites-pull-request-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN_TEST_RM }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_TEST_RM }}
        timeout-minutes: 1
